image: oven/bun:alpine
 
stages:
    - build
    - deploy

cache:
  paths:
    - ./front/website/node_modules/

build:
  stage: build
  only:
    - main
  before_script:
    #Website
    - rm -rf dist    
    - CI=false bun install
    #Compress
    - apk add --no-cache brotli
    - apk add --no-cache zstd
  script:
    #Website
    - CI=false bun run build $BUILD_ARGS
    #Compress
    - find dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\|pdf\)$' -exec gzip -f -k -9 {} \;
    - find dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\|pdf\)$' -exec brotli -f -k -Z {} \;
    - find dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\|pdf\)$' -exec zstd -f -k --ultra -22 -q {} \;
  artifacts:
        paths:
          - dist

pages:
  stage: deploy
  only:
    - main
  dependencies:
    - build
  script:
    - mkdir deploy
    - mv dist/* deploy
  environment: 
    name: Production
  artifacts:
    paths:
      - deploy

