image: oven/bun:alpine
 
stages:
    - build
    - deploy

cache:
  paths:
    - ./orm/node_modules/

build:
  stage: build
  only:
    - main
  before_script:
    #Website
    - cd ./orm
    - rm -rf dist    
    - CI=false bun install
    - cd ..
    #Compress
    - apk add --no-cache brotli
    - apk add --no-cache zstd
  script:
    #Website
    - cd ./orm
    - CI=false bun run build $BUILD_ARGS
    - cd ..
    - mkdir build
    - mv ./orm/dist/* build 
    #Compress
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\|pdf\)$' -exec gzip -f -k -9 {} \;
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\|pdf\)$' -exec brotli -f -k -Z {} \;
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\|pdf\)$' -exec zstd -f -k --ultra -22 -q {} \;
  artifacts:
        paths:
          - build

pages:
  stage: deploy
  only:
    - main
  dependencies:
    - build
  script:
    - ls ./build 
    - mkdir public
    - mv build/* public
    - ls ./public 
  environment: 
    name: Production
  artifacts:
    paths:
      - public

